// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsProfile = {
  // Automaticky generovaný sidebar ze složky profile-docs
  profileSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsProfile;
